name: CVRacing
main: org.cubeville.cvracing.CVRacing
authors: [Ptown16]
version: 0.1
api-version: 1.18
depend: [CVTools]
description: This is a plugin for time trials racing on the server cubeville.org!

commands:
  race:
    description: CVRacing Base Command

permissions:
  cvboatrace.checkpoints.add:
    description: Add a checkpoint to a track. Must be looking at a tripwire hook to set a checkpoint!
    default: op

  cvboatrace.checkpoints.delete:
    description: Delete a checkpoint for a track at a specific index.
    default: op

  cvboatrace.checkpoints.list:
    description: List all checkpoints for a track.
    default: op

  cvboatrace.leaderboards.add:
    description: Add a leaderboard displaying top times for a track.
    default: op

  cvboatrace.leaderboards.delete:
    description: Delete a leaderboard for a track at a specific index.
    default: op

  cvboatrace.leaderboards.list:
    description: List all leaderboards for a track.
    default: op

  cvboatrace.leaderboard:
    description: View the leaderboard for a track.
    default: true

  cvboatrace.signs.add:
    description: Add a race sign for a track.
    default: op

  cvboatrace.signs.delete:
    description: Delete a race sign for a track at a specific index.
    default: op

  cvboatrace.signs.list:
    description: List all race signs for a track.
    default: op

  cvboatrace.track.create:
    description: Create a track.
    default: op

  cvboatrace.track.delete:
    description: Delete a track.
    default: op

  cvboatrace.track.close:
    description: Close a track from being used.
    default: op

  cvboatrace.track.open:
    description: Open a track to allow it to be used.
    default: op

  cvboatrace.track.setexit:
    description: Set the exit point for a track.
    default: op

  cvboatrace.track.setspawn:
    description: Set the spawn point for a track.
    default: op

  cvboatrace.scores.clear:
    description: Clear all scores on a specific track.
    default: op

  cvboatrace.scores.delete:
    description: Delete a player's score on a specific track.
    default: op

  cvboatrace.pb:
    description: View your personal best time for a track.
    default: true

  cvboatrace.rank:
    description: View your ranking for a track.
    default: true

  cvboatrace.help:
    description: View all commands for cvboatrace.
    default: true

  cvboatrace.splits.compare:
    description: Compare splits gotten on a track between multiple players.
    default: true

  cvboatrace.splits.use:
    description: Use another user's splits for a race.
    default: true



